feat: Incorrect title added to the sentence that follows it #77
cuixueshe/earthworm pull request #104
Opened 2024-02-01 02:46 UTC by myltx

关联 issue #77 

### 实现思路

- 具体实现参考的多邻国的功能
- 当某一题目第一次输入错误后，题目会通过`push` 添加到当前课程末尾，课程进度随之延长，同一课程的同一题目多次输入错误只会添加一次；

#### 错题添加：

- 在 `Question.vue` 的 `handleKeyup` 中当回车事件后校验答案错误，然后就将当前题目复制到`currentIncorrectQuestion` 并且设置新的 `id` ，并将原有 `id` 赋值给`incorrectQuestionId` 字段，用于在下次输入错误时校验当前题目是否已经在错题数组中；
- 将处理后的 `currentIncorrectQuestion` 添加到  `courseStore.currentCourse?.statements` 中，并将其缓存在 `localStorage`的 `courseIncorrectQuestion` 中 ；
- 在 `course.ts` 中添加 `useIncorrectQuestion` 用于处理错题的添加、删除、获取，在 `setUp` 时调用 `loadIncorrectQuestion` 获取到缓存的错题，然后与接口返回的数据合并（解决页面刷新后错题回显）；

#### 错题清空：

- 在结算页点击 `再来一次` 或者 `开始下一课` 时调用 `resetCurrentCourse` 清空缓存的错题数据；

2024-02-02 08:55 UTC, Nauxscript requested changes

2024-02-02 08:55 UTC, Nauxscript commented on scripts/course/courses/04.json
> -		"english": "it doesn't have to",
尽量避免在一个提交中进行多个 feat 和 fix 混合，保持一个 pr 对应一个 feat / fix

2024-02-02 09:28 UTC, myltx commented on scripts/course/courses/04.json
> -		"english": "it doesn't have to",
好的  后边会创建不同的分支进行不同的  pr

2024-02-04 04:53 UTC, hildxd commented
感谢 pr，能否尝试着补充下测试？

2024-02-04 04:57 UTC, hildxd commented
崔哥要重构这块数据结构，先关了，感谢感谢

2024-02-04 04:57 UTC, closed without merging

2024-02-04 08:19 UTC, myltx commented
好的  后边有需要我再贡献，下次参与贡献会添加测试