feat: command for messagebox
cuixueshe/earthworm pull request #147
Opened 2024-02-07 09:31 UTC by SinglePoi

以命令方式打开 MessageBox()
### 使用方式
```typescript
MessageBox(content, title, options)
.then((action) => {
// this action is confirm
}).catch((action) => {
// this action is cancel
})
```
### 可选参数
``` typescript
content: string = "Are you sure?",
title: string = "Tips",
options: {
  confirmBtnText: "Confirm",
  cancelBtnText: "Cancel",
}
```
### 示例
```typescript
let msgAction = "";
MessageBox("此操作将永久删除该文件, 是否继续?", "提示").then((action) => {
   msgAction = action;
});
```

### 更多 
👉  message-box.spec.ts

2024-02-08 00:13 UTC, SinglePoi commented
糟糕，忘记补上类型了😅

2024-03-02 10:26 UTC, Nauxscript commented
挺好，如果后续可以再封装一个可以命令调用的 `Toast` 组件就更好了🤩 这样就可以完全去掉 `naive-ui` 了 #179

2024-03-11 01:49 UTC, Nauxscript commented
麻烦解决一下冲突😁

2024-03-12 02:20 UTC, Nauxscript commented
可以把 `MessageBox.ts` `MessageBox.vue` 以及其测试都放在一个文件夹中，这样目录架构更清晰

2024-03-12 02:20 UTC, Nauxscript requested changes

2024-03-12 02:20 UTC, Nauxscript commented on apps/client/components/main/tests/message-box.spec.ts
> +const rAF = async () => {
`rAF` 这个方法可以换成 `@vue/test-utils` 中的 `flushPromises`

2024-03-12 02:20 UTC, Nauxscript commented on apps/client/components/main/tests/message-box.spec.ts
> +    await rAF();
替换为 `flushPromises`；可以减少代码的冗余，提高代码可读性。以下几个地方的也同理。

2024-03-12 04:16 UTC, Nauxscript approved these changes

2024-03-12 05:50 UTC, merged

2024-03-12 05:50 UTC, Nauxscript commented
LGTM! Thanks!