refactor: 重构课程包首页样式 #656
cuixueshe/earthworm pull request #657
Opened 2024-04-29 11:15 UTC by orangelckc

先把布局改了，课程包卡片样式等拿到数据再来改
![image](https://github.com/cuixueshe/earthworm/assets/48410934/46ca9bcd-33f8-4949-a50c-cd0d0fb28f56)

2024-04-29 11:56 UTC, orangelckc commented
改完了，请验收～
![image](https://github.com/cuixueshe/earthworm/assets/48410934/f900c580-42e4-496c-81a7-4da89e3b74ca)

2024-04-30 03:24 UTC, hildxd requested changes
添加一下头像容器的最小宽度 不然变形，然后把勋章那部分用 v-if 影响，我改好了 push 不到你仓库 害

2024-04-30 04:07 UTC, fengstats commented
related to #656

2024-04-30 09:18 UTC, orangelckc commented
> 添加一下头像容器的最小宽度 不然变形，然后把勋章那部分用 v-if 影响，我改好了 push 不到你仓库 害
![image](https://github.com/cuixueshe/earthworm/assets/48410934/f91f4f54-e2f1-4212-a2f7-60cd89491be3)

呃，应该是可以提交的，我先改一下吧

2024-05-10 08:07 UTC, merged