fix: user avatar placeholder using transparent GIF
cuixueshe/earthworm pull request #702
Opened 2024-05-28 11:19 UTC by orangelckc

#698 
使用 1x1 像素的透明 GIF 图片，消除头像图片加载失败时的边框

2024-05-28 12:11 UTC, baboon-king requested changes
非常巧妙的办法！🥳
但是你能试试这个吗
在 apps/client/components/Home/index.vue L5-L12 使用下面的代码
```html
<div
  class="mx-auto h-56 w-56 overflow-hidden rounded-full border-2 border-gray-300 bg-gray-300 dark:border-gray-700 dark:bg-gray-700"
>
  <img
    class="h-full object-cover"
    :src="userStore.userInfo?.picture!"
  />
</div>
```
这样的话，我们或许可以，不用采用这么[魔法](https://github.com/cuixueshe/earthworm/pull/702/files)的方式，

2024-05-29 09:59 UTC, orangelckc commented
> 非常巧妙的办法！🥳 但是你能试试这个吗 在 apps/client/components/Home/index.vue L5-L12 使用下面的代码
> 
> ```
> <div
>   class="mx-auto h-56 w-56 overflow-hidden rounded-full border-2 border-gray-300 bg-gray-300 dark:border-gray-700 dark:bg-gray-700"
> >
>   <img
>     class="h-full object-cover"
>     :src="userStore.userInfo?.picture!"
>   />
> </div>
> ```
> 
> 这样的话，我们或许可以，不用采用这么[魔法](https://github.com/cuixueshe/earthworm/pull/702/files)的方式，

感谢，这么看是我想麻烦了，有点思维定势了😓

那这个PR我就关掉啦～

2024-05-29 10:02 UTC, baboon-king commented
> > 非常巧妙的办法！🥳 但是你能试试这个吗 在 apps/client/components/Home/index.vue L5-L12 使用下面的代码
> > ```
> > <div
> >   class="mx-auto h-56 w-56 overflow-hidden rounded-full border-2 border-gray-300 bg-gray-300 dark:border-gray-700 dark:bg-gray-700"
> > >
> >   <img
> >     class="h-full object-cover"
> >     :src="userStore.userInfo?.picture!"
> >   />
> > </div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样的话，我们或许可以，不用采用这么[魔法](https://github.com/cuixueshe/earthworm/pull/702/files)的方式，
> 
> 感谢，这么看是我想麻烦了，有点思维定势了😓
> 
> 那这个PR我就关掉啦～

你可以更新你现在的代码，然后重新提交。我们依然可以继续合并这个PR🥳

2024-05-29 21:50 UTC, fengstats commented
不错的思路~ 爱了 😊

2024-05-29 22:12 UTC, merged